### DISCUSSION TITLE
What's the difference between settings and fields?

### DISCUSSION THREAD

**Discussion by justintemps** [wingsuit-designsystem/wingsuit#272] [Q&A]
It looks like they accomplish the exact same thing, the docs aren't very specific about when to use which one...

**Comment by christianwiedemann** [comment]
Hi, a setting is a simple value. A field a render array. In VUE for example. slot=field, prop = setting

**Reply by justintemps** [reply]
@christianwiedemann Thanks the for the fast answer! But just for my own peace of mind, Twig templates don't actually support this distinction right? They just take data.

**Reply by justintemps** [reply]
Also, can I set different default settings for each variant?

**Reply by christianwiedemann** [reply]
Yes. You can define a setting value for a variant. For example you have a setting text-align and in your card variant horizontal the text alignment is always letft you define this in your variant.

**Reply by justintemps** [reply]
Thanks so much for your help @christianwiedemann! But I'm still a bit confused. let's say I have a hero component

```yaml
hero:
  use: "@components/hero/hero.twig"
  label: Hero
  fields:
    image:
      type: string
  settings:
    theme:
      label: Theme
      required: false
      preview: "dark"
      options:
        dark: Dark
        light: Light
  variant:
    light:
      settings:
        theme: "light"    
```

In the preview of my `light` variant, the `theme` settings are missing from my arguments table and the value isn't set on the preview.
