### ISSUE TITLE
libraries

### ISSUE THREAD

**Issue by woldtwerk** [wingsuit-designsystem/wingsuit#142]
This is just a request for some info.

What do you need to do to make drupal register libraries defined in patterns?

this is my yml:

```
literature_references:
  use: "@molecules/literature-references/literature-references.twig"
  label: Literature References
  libraries:
    - pattern_literature_references:
        js:
          ../behaviors/literature-references.js: {}
```
I also have the literature-references.js in there. It get's compiled into the dist/behaviours correctly and I can also use it in storybook when imported in the index.js

How do I tell Drupal to pick it up?
