### ISSUE TITLE
Pattern twig function not respecting variant

### ISSUE THREAD

**Issue by jowan** [wingsuit-designsystem/wingsuit#172]
**Describe the bug**

When I pass a variant to the pattern twig function it is ignored.
It does work with pattern_preview though.

**To Reproduce**

Use both pattern and pattern_preview in a template with a variant and compare results.

**Expected behavior**

pattern twig function should respect variant and load what ever settings are bundled in that variant.

**Screenshots**

Screen shot of rendered template:

![image](https://user-images.githubusercontent.com/16796/124754776-80570200-df22-11eb-9d55-7b6d3aa2a53c.png)

**Additional context**

Here is my template, calling both pattern and pattern preview:

```twig
<div id="ac-{{ pid }}" class="accordion">
  {% for link in links %}
    {% set vars = {
      "pid": pid,
      "aiid": link.aiid,
      "label": link.label,
      "content": link.content,
    } %}
    {{ pattern('bs_accordion_item', vars, 'aci_c') }}
    {{ pattern_preview('bs_accordion_item', vars, 'aci_c') }}
  {% endfor %}
</div>
```

And here is my sub template's (the one being called above) wingsuit.yml:

```yml
bs_accordion_item:
  namespace: "Molecules/TM - Bootstrap"
  use: "@molecules/tm-bs/accordion-item/accordion-item.twig"
  label: Accordion Item
  description: A collapsible accordion item without javascript.
  fields:
    label:
      type: text
      label: Label
      description: The accordion item label.
      preview:
        faker: lorem.word
    content:
      type: text
      label: Content
      description: The collapsed content.
      preview:
        faker: lorem.paragraph
    aiid:
      type: text
      label: Item ID
      description: ID of the accordion-item
      preview:
        faker: lorem.slug
  settings:
    pid:
      type: textfield
      label: Parent ID
      description: ID of the parent
    toggle:
      type: select
      label: Toggle
      description: The icon used for collapse.
      options:
        sign: Sign
        chevron: Chevron
    content_class:
      type: textfield
      label: Content class
      description: Content class
    content_attributes:
      type: attributes
      label: Content attributes
      description: Content attributes
    link_attributes:
      type: attributes
      label: Link attributes
      description: Link attributes
    link_class:
      type: textfield
      label: Link class
      description: Link class
  variants:
    __default:
      label: Default
      description: Default
    aci_a:
      label: Version A
      description: Version A
      settings:
        toggle: chevron
        link_class: card-header
        content_class: card-body
    aci_b:
      label: Version B
      description: Version B
      settings:
        toggle: sign
        link_class: accordion-button
        content_class: accordion-body
    aci_c:
      label: Version C
      description: Version C
      settings:
        toggle: sign
        link_class: aci-c-link
        content_class: aci-c-content
```

I think that pattern(patternID, vars, variantID) should apply my variant here, which just contains some classes.

Thanks for your help :)
