### ISSUE TITLE
Using data source files with story.wingsuit.yml

### ISSUE THREAD

**Issue by jowan** [wingsuit-designsystem/wingsuit#183]
Is there a way to use a data file e.g ./data.json with wingsuit ?
Modelling the data as yml in an object type field can get pretty unwieldy pretty quickly.
I do it with Twig and Storybook ok, but would really like a way of doing it within the story.wingsuit.yml, e.g

```yml

my_pattern:
  namespace: "Templates/Utilities"
  use: "@templates/utilities/my-pattern.twig"
  label: My Pattern
  
  fields:
    data:
      type: datafile
      label: Data
      preview: './my-data.json'

```

any thoughts ?
