### ISSUE TITLE
Pattern definition 

### ISSUE THREAD

**Issue by christianwiedemann** [wingsuit-designsystem/wingsuit#3]
**We need a reference pattern:**

**Main Template:**
- Twig template
- CSS file
- README.md

**Demo Template:**
- Twig template
- README.md
- demo yml

**Comment by christianwiedemann** [comment]
**Proposed solution:**

**I want to pitch following idea:**

Base of each pattern is adjusted ui_patterns.yml which is part of the main pattern. So each pattern describes itself with pattern.wingsuit.yml.  

**Example Card Pattern:**
`card.wingsuit.yml`
```
card:
  use: "@molecules/card/_card.twig"
  label: Card
  description: Pattern for card.
  fields:
    image:
      type: image
      label: Image
    preheadline:
      type: text
      label: Preheadline
    headline:
      type: text
      label: Headline
    content:
      type: text
      label: Content
  variants:
    horizontal:
      label: Horizontal
  settings:
    url:
      type: token
      label: Url
    element:
      type: textfield
      label: Element

```
