### ISSUE TITLE
Problem enabling the drupal theme

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#52]
**Describe the bug**
Enabling and setting drupal theme leads to WSOD 

**To Reproduce**
Setup a clean latest drupal and wingsuit drupal theme (similar to these steps https://github.com/wingsuit-designsystem/wingsuit/issues/43)
and than enable the theme and set as default

error message from the watchdog 
```
Twig\Error\LoaderError: The "themes/custom/wingsuit/apps/drupal/../../dist/app-drupal/assets/atomic/patterns/01-atoms" directory does not exist ("/app/web/themes/custom/wingsuit/apps/drupal/../../dist/app-drupal/assets/atomic/patterns/01-atoms"). in Twig\Loader\FilesystemLoader->addPath() (line 106 of /app/vendor/twig/twig/src/Loader/FilesystemLoader.php).
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser latest Chrome

**Workaround**
Dropping `/assets`  from the paths in the `wingsuite.info.yml` file 

```
component-libraries:
  protons:
    paths: []
  atoms:
    paths:
      - ../../dist/app-drupal/assets/atomic/patterns/01-atoms
  molecules:
    paths:
      - ../../dist/app-drupal/assets/atomic/patterns/02-molecules
  organisms:
    paths:
      - ../../dist/app-drupal/assets/atomic/patterns/03-organisms
  templates:
    paths:
      - ../../dist/app-drupal/assets/atomic/patterns/04-templates

```

solved the problem 
why are those 2 directories with similar content needed ? 
`dist/app-drupal/assets/atomic` == `dist/app-drupal/atomic`
