### ISSUE TITLE
Configuration inheritance

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#58]
I think a configuration inheritance would be very beneficial to the developer 

A simple version would work something like this 

we could have a `default.wingsuit.yml` with content like this
```yml
  settings_standard:
    width:
      type: select
      label: Width
      default_value: default
      required: true
      preview: default
      options:
        small: Small
        default: Default
        large: Large
    bg:
      type: select
      label: Background color
      options:
        gray-medium: Medium gray
        gray-light: Light gray
```

Now in a pattern1.wingsuit.yml we could have 
```yml
  settings: 
    default.settings_standard.width
    padding:
 # ...
```
which would bring in the settings of `width`

but in another `pattern2.wingsuit.yml` we could have

```yml
  settings:
    default.settings_standard
```
we could inherit ALL `settings_standard` 

but we could go further and inherit from other patterns 

```yml
  settings:
    pattern1.settings.padding
```

The alternative I see for now is copy/paste of settings that are common which leads to lots of duplication especially if one decides to have a lot of very similar settings for a lot of patterns.

The examples above focus on settings but perhaps I see it might be helpful for any settings that go inside a wingsuit file.

Let me know if this is doable or if you need any further explanation or if you see any alternatives or workarounds.

I will be available for testing or perhaps even helping ironing any code problems if you decide to implement it.

Let me NOTE that I have once worked with fractal and they do have a [configuration inheritance](https://fractal.build/guide/core-concepts/configuration-files.html#configuration-inheritance) which was very helpful.
