### ISSUE TITLE
ws-assets in libraries.yml does not get replaced with actual path

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#59]
**To Reproduce**
when creating a component with `wc-generate-component`
in yml file we get something like this 

```yml
  libraries:
    - pattern_PATTERNNAME:
        css:
          component:
            ws-assets://PATTERNNAME.css: {}
```
but after building the theme we get 404 file not found in console the file the browser is looking for is 
`https://domain/themes/custom/wingsuit/dist/app-drupal/wingsuit/ws-assets%3A//PATTERNNAME.css`

For now workaround is to use 
```yml
  libraries:
    - pattern_PATTERNNAME:
        css:
          component:
            ../PATTERNNAME.css: {}
```
